title: "Modern Alki Beach Townhome – 3 Bed · Rooftop Deck · No HOA"
description: "Light-filled 2020-built townhome in West Seattle, just blocks from the beach. Features include an open-concept main level, oversized primary suite, energy-efficient mini-splits, and a spacious rooftop deck. Walkable to Alki Trail, coffee shops, and restaurants. Listed at $849,000 — no HOA fees."

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - README.md
  
include:
  - _pages
