url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "3019 62nd Ave SW, Unit D, Seattle, WA 98116" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss

postcss:
  cache: false

css_dir: "styles"

include:
  - _pages/